services:
  - type: web
    name: keystroke-auth-backend
    env: python
    runtime: python-3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT collection:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    
  - type: web
    name: keystroke-auth-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://keystroke-auth-backend.onrender.com 